/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nvip.plugfest.tooling;

import java.io.File;
import java.io.IOException;

import org.nvip.plugfest.tooling.differ.Comparer;
import org.nvip.plugfest.tooling.differ.DiffReport;
import org.nvip.plugfest.tooling.qa.QAPipeline;
import org.nvip.plugfest.tooling.qa.QualityReport;
import org.nvip.plugfest.tooling.sbom.*;
import org.nvip.plugfest.tooling.translator.TranslatorSPDX;
import org.nvip.plugfest.tooling.translator.TranslatorPlugFest;


public class Main {

    private static final int MIN_ARGS = 2;

    /**
     * FileName: Main.java
     * Receives a list of files, outputs SBOM comparisons.
     *
     * @param args
     */
    public static void main(String[] args) {

        if (args.length < MIN_ARGS)
            System.out.println(
                    "Too few arguments. Requires: at least two files.\n" +
                            "Example: users/admin/files/1.xml users/admin/files/2.xml");
        System.exit(0);

        // check all files exist
        for (String f: args
             ) {

            if(!new File(f).exists()) {
                System.out.println("Second file can not be found. Exiting...");
                System.exit(0);
            }

        }

        //todo
        
    }
}
