/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package plugfest.tooling;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest);
    }
}
